name: Cypress Component Tests

on:
  push:
    branches:
      - UnitTesting

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command : yarn cypress run-ct
