name: Cypress Tests

on:
  push:
    branches:
      - UnitTesting

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2




      - name: Run Cypress Tests
        run: cypress-io/github-action@v2
